from __future__ import annotations


def final_dataset_sql() -> str:
    return """
    CREATE TABLE "{target_schema}"."ml_dataset" AS
    WITH joined AS (
        SELECT
            p.patientunitstayid,
            p.patienthealthsystemstayid,
            p.hospitalid,
            p.gender,
            p.age_years,
            p.age_group,
            p.ethnicity,
            p.admissionheight,
            p.admissionweight,
            p.hospitaladmitsource,
            p.hospitaldischargestatus,
            p.unitadmitsource,
            p.unitdischargestatus,
            p.unitdischargeoffset,
            p.hospitaldischargeoffset,
            p.icu_los_hours,
            p.hospital_los_hours,
            p.icu_stay_category,
            p.apacheadmissiondx,
            p.hospital_mortality,
            p.unit_mortality,
            l.lab_row_count,
            l.lab_name_count,
            l.first_lab_offset,
            l.last_lab_offset,
            l.lab_result_mean,
            l.lab_result_min,
            l.lab_result_max,
            l.creatinine_mean,
            l.creatinine_max,
            l.glucose_mean,
            l.glucose_min,
            l.glucose_max,
            l.lactate_mean,
            l.lactate_max,
            l.wbc_mean,
            l.wbc_max,
            l.potassium_mean,
            l.potassium_min,
            l.potassium_max,
            l.sodium_mean,
            l.hemoglobin_mean,
            l.hemoglobin_min,
            l.platelet_mean,
            l.platelet_max,
            v.vital_row_count,
            v.first_vital_offset,
            v.last_vital_offset,
            v.temperature_mean,
            v.temperature_min,
            v.temperature_max,
            v.sao2_mean,
            v.sao2_min,
            v.heartrate_mean,
            v.heartrate_min,
            v.heartrate_max,
            v.respiration_mean,
            v.respiration_max,
            v.sbp_mean,
            v.sbp_min,
            v.sbp_max,
            v.dbp_mean,
            v.map_mean,
            v.heartrate_trend,
            v.temperature_trend,
            v.sao2_trend,
            d.diagnosis_row_count,
            d.diagnosis_distinct_count,
            d.dx_sepsis_flag,
            d.dx_respiratory_flag,
            d.dx_cardiac_flag,
            d.dx_renal_flag
        FROM "{target_schema}"."patient_base_clean" p
        LEFT JOIN "{target_schema}"."lab_features" l
            ON p.patientunitstayid = l.patientunitstayid
        LEFT JOIN "{target_schema}"."vital_features" v
            ON p.patientunitstayid = v.patientunitstayid
        LEFT JOIN "{target_schema}"."diagnosis_features" d
            ON p.patientunitstayid = d.patientunitstayid
    ),
    numeric_stats AS (
        SELECT
            percentile_cont(0.5) WITHIN GROUP (ORDER BY admissionheight) AS admissionheight_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY admissionweight) AS admissionweight_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY creatinine_max) AS creatinine_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY glucose_min) AS glucose_min_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY glucose_max) AS glucose_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY lactate_max) AS lactate_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY wbc_max) AS wbc_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY heartrate_mean) AS heartrate_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY heartrate_max) AS heartrate_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY heartrate_min) AS heartrate_min_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY sao2_mean) AS sao2_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY sao2_min) AS sao2_min_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY respiration_mean) AS respiration_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY respiration_max) AS respiration_max_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY sbp_mean) AS sbp_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY map_mean) AS map_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY sbp_min) AS sbp_min_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY temperature_mean) AS temperature_mean_med,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY temperature_max) AS temperature_max_med
        FROM joined
    )
    SELECT
        j.patientunitstayid,
        j.patienthealthsystemstayid,
        j.hospitalid,
        j.hospital_mortality,
        j.unit_mortality,
        j.age_years,
        j.icu_los_hours,
        j.hospital_los_hours,
        CASE WHEN j.admissionheight IS NULL THEN 1 ELSE 0 END AS admissionheight_missing_flag,
        CASE WHEN j.admissionweight IS NULL THEN 1 ELSE 0 END AS admissionweight_missing_flag,
        CASE WHEN j.creatinine_max IS NULL THEN 1 ELSE 0 END AS creatinine_missing_flag,
        CASE WHEN j.glucose_max IS NULL THEN 1 ELSE 0 END AS glucose_missing_flag,
        CASE WHEN j.lactate_max IS NULL THEN 1 ELSE 0 END AS lactate_missing_flag,
        CASE WHEN j.wbc_max IS NULL THEN 1 ELSE 0 END AS wbc_missing_flag,
        CASE WHEN j.heartrate_mean IS NULL THEN 1 ELSE 0 END AS heartrate_missing_flag,
        CASE WHEN j.sao2_mean IS NULL THEN 1 ELSE 0 END AS sao2_missing_flag,
        CASE WHEN j.respiration_mean IS NULL THEN 1 ELSE 0 END AS respiration_missing_flag,
        CASE WHEN j.sbp_mean IS NULL THEN 1 ELSE 0 END AS sbp_missing_flag,
        CASE WHEN j.map_mean IS NULL THEN 1 ELSE 0 END AS map_missing_flag,
        CASE WHEN j.temperature_mean IS NULL THEN 1 ELSE 0 END AS temperature_missing_flag,
        CASE WHEN j.lab_row_count IS NULL THEN 1 ELSE 0 END AS lab_missing_flag,
        CASE WHEN j.vital_row_count IS NULL THEN 1 ELSE 0 END AS vital_missing_flag,
        coalesce(j.admissionheight, s.admissionheight_med, 0) AS admissionheight,
        coalesce(j.admissionweight, s.admissionweight_med, 0) AS admissionweight,
        coalesce(j.creatinine_max, s.creatinine_max_med, 0) AS creatinine_max,
        coalesce(j.glucose_max, s.glucose_max_med, 0) AS glucose_max,
        coalesce(j.glucose_min, s.glucose_min_med, 0) AS glucose_min,
        coalesce(j.lactate_max, s.lactate_max_med, 0) AS lactate_max,
        coalesce(j.wbc_max, s.wbc_max_med, 0) AS wbc_max,
        coalesce(j.heartrate_mean, s.heartrate_mean_med, 0) AS heartrate_mean,
        coalesce(j.heartrate_max, s.heartrate_max_med, 0) AS heartrate_max,
        coalesce(j.heartrate_min, s.heartrate_min_med, 0) AS heartrate_min,
        coalesce(j.sao2_mean, s.sao2_mean_med, 0) AS sao2_mean,
        coalesce(j.sao2_min, s.sao2_min_med, 0) AS sao2_min,
        coalesce(j.respiration_mean, s.respiration_mean_med, 0) AS resp_mean,
        coalesce(j.respiration_max, s.respiration_max_med, 0) AS resp_max,
        coalesce(j.sbp_mean, s.sbp_mean_med, 0) AS sbp_mean,
        coalesce(j.sbp_min, s.sbp_min_med, 0) AS sbp_min,
        coalesce(j.map_mean, s.map_mean_med, 0) AS map_mean,
        coalesce(j.temperature_mean, s.temperature_mean_med, 0) AS temp_mean,
        coalesce(j.temperature_max, s.temperature_max_med, 0) AS temp_max,
        coalesce(j.lab_row_count, 0) AS lab_row_count,
        coalesce(j.vital_row_count, 0) AS vital_row_count,
        coalesce(j.diagnosis_row_count, 0) AS diagnosis_row_count,
        coalesce(j.dx_sepsis_flag, 0) AS dx_sepsis_flag,
        coalesce(j.dx_respiratory_flag, 0) AS dx_respiratory_flag,
        coalesce(j.dx_cardiac_flag, 0) AS dx_cardiac_flag,
        coalesce(j.dx_renal_flag, 0) AS dx_renal_flag,
        CASE WHEN lower(coalesce(j.gender, 'unknown')) = 'male' THEN 1 ELSE 0 END AS gender_male,
        CASE WHEN lower(coalesce(j.gender, 'unknown')) = 'female' THEN 1 ELSE 0 END AS gender_female,
        CASE WHEN lower(coalesce(j.gender, 'unknown')) NOT IN ('male', 'female') THEN 1 ELSE 0 END AS gender_unknown,
        CASE WHEN lower(coalesce(j.ethnicity, 'unknown')) LIKE '%asian%' THEN 1 ELSE 0 END AS ethnicity_asian,
        CASE WHEN lower(coalesce(j.ethnicity, 'unknown')) LIKE '%caucasian%' OR lower(coalesce(j.ethnicity, 'unknown')) LIKE '%white%' THEN 1 ELSE 0 END AS ethnicity_white,
        CASE WHEN lower(coalesce(j.ethnicity, 'unknown')) LIKE '%african%' OR lower(coalesce(j.ethnicity, 'unknown')) LIKE '%black%' THEN 1 ELSE 0 END AS ethnicity_black,
        CASE WHEN lower(coalesce(j.ethnicity, 'unknown')) LIKE '%hispanic%' OR lower(coalesce(j.ethnicity, 'unknown')) LIKE '%latino%' THEN 1 ELSE 0 END AS ethnicity_hispanic,
        CASE WHEN lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%asian%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%caucasian%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%white%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%african%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%black%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%hispanic%' AND lower(coalesce(j.ethnicity, 'unknown')) NOT LIKE '%latino%' THEN 1 ELSE 0 END AS ethnicity_other,
        CASE WHEN j.age_group = 'young' THEN 1 ELSE 0 END AS age_group_young,
        CASE WHEN j.age_group = 'adult' THEN 1 ELSE 0 END AS age_group_adult,
        CASE WHEN j.age_group = 'senior' THEN 1 ELSE 0 END AS age_group_senior,
        CASE WHEN j.icu_stay_category = 'short' THEN 1 ELSE 0 END AS icu_stay_short,
        CASE WHEN j.icu_stay_category = 'medium' THEN 1 ELSE 0 END AS icu_stay_medium,
        CASE WHEN j.icu_stay_category = 'long' THEN 1 ELSE 0 END AS icu_stay_long,
        ((coalesce(j.respiration_mean, 0) >= 22)::int + (coalesce(j.sbp_min, 999) <= 100)::int) AS qsofa_score
    FROM joined j
    CROSS JOIN numeric_stats s;
    """
